language: objective-c
osx_image: xcode7
xcode_project: Framework/YYText.xcodeproj
xcode_scheme: YYText

script:
- xctool -project Framework/YYText.xcodeproj -scheme YYText build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO